### ISSUE TITLE
Basic Note Send failed with: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by mikeriss** [ocknamo/n8n-nodes-nostrobots#8]
Basic Note Send failed with: Cannot read properties of undefined (reading 'message')

![image](https://github.com/ocknamo/n8n-nodes-nostrobots/assets/5846456/57642d09-8f3a-4a7a-8e57-1da1c288a945)

**Comment by mikeriss** [comment]
is this repo still active?

**Comment by ocknamo** [comment]
@mikeriss 

Sorry for the late reply.
I could not reproduce the problem in my environment below.

n8n: v0.234.1
n8n-nodes-nostrobots: v0.2.1

It would be helpful if you could tell me what version you ran.

Also, if you could give me a json export of the workflow you ran, it would help me verify the issue.
You can get export menu the right of header in the workflow page.

Thank you for your report.

**Comment by mikeriss** [comment]
n8n: Version 1.7.1
n8n-nodes-nostrobots: v0.2.1

Its just a simple workflow to test writing to nostr.
the export: 
{
  "name": "My workflow",
  "nodes": [
    {
      "parameters": {},
      "id": "9ba681e2-6cf0-4418-a55d-fd29a706689c",
      "name": "When clicking \"Execute Workflow\"",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [
        40,
        340
      ]
    },
    {
      "parameters": {
        "resource": "event",
        "content": "hi"
      },
      "id": "c31ea78d-47a6-4df9-8b1e-ec61f49cc8e8",
      "name": "Nostr Write",
      "type": "n8n-nodes-nostrobots.nostrobots",
      "typeVersion": 1,
      "position": [
        320,
        340
      ],
      "credentials": {
        "nostrobotsApi": {
          "id": "FBoobR6Aefq5mrkZ",
          "name": "Nostrobots account 2"
        }
      }
    }
  ],
  "pinData": {},
  "connections": {
    "When clicking \"Execute Workflow\"": {
      "main": [
        [
          {
            "node": "Nostr Write",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {
    "saveManualExecutions": true,
    "callerPolicy": "workflowsFromSameOwner",
    "executionOrder": "v0",
    "errorWorkflow": "3"
  },
  "versionId": "d5452514-85f1-48b6-8386-ffd720035095",
  "id": "16",
  "meta": {
    "instanceId": "89b743c96f6e3710b9eb9c884be42818fd31ed517ce9e297b5ae6729cb1f1e24"
  },
  "tags": []
}

**Comment by ocknamo** [comment]
@mikeriss 
I reproduced your workflow with matching software versions and it ran successfully with no errors.

It seems that we does not have enough information to solve the problem.

If you have more time, I would like you to try using ErrorTrigger to get stacktrace of the error.

Please refer to the following document to set up the error workflow for the target workflow.

https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.errortrigger/#related-resources

However, the error workflow can only be used for automatic execution, so you need to change to use Schedule Trigger instead of manual triggers.

**Comment by ocknamo** [comment]
@mikeriss 
I have found that this problem occurs when certain relays are used.
I believe this problem has been resolved as a result of correcting error handling and timeouts.

Please check with the latest version!

https://github.com/ocknamo/n8n-nodes-nostrobots/pull/16

**Comment by ocknamo** [comment]
Closed because this issue has been resolved.
